// frontend/src/containers/modal/islandCity/Info.tsx
import React from "react";
import { useTranslation } from "react-i18next";

interface CityData {
  city: {
    name: string;
    level: number;
    user: string;
  };
}

interface InfoProps {
  data: CityData;
}

const Info: React.FC<InfoProps> = ({ data }) => {
  const { t } = useTranslation();

  return (
    <div className="text-sm leading-tight">
      <div className="flex my-1">
        <div className="flex-1">{t("modal.islandCity.name")}:</div>
        <div className="flex-2">
          {data.city.name} ({data.city.level})
        </div>
      </div>

      <div className="flex my-1">
        <div className="flex-1">{t("modal.islandCity.player")}:</div>
        <div className="flex-2">{data.city.user}</div>
      </div>

      <div className="flex my-1">
        <div className="flex-1">{t("modal.islandCity.alliance")}:</div>
        <div className="flex-2">-</div>
      </div>

      <div className="flex my-1">
        <div className="flex-1">{t("modal.islandCity.points")}:</div>
        <div className="flex-2">-</div>
      </div>
    </div>
  );
};

export default Info;

// resources/game/components/modal/IslaCiudad/Info.vue
<template>
    <div class="box">
        <div class="d-flex my-1">
            <div class="flex-1">{{$t('actions.info.name')}}:</div>
            <div class="flex-2">{{data.city.name}} ({{data.city.level}})</div>
        </div>
        <div class="d-flex my-1">
            <div class="flex-1">{{$t('actions.info.player')}}:</div>
            <div class="flex-2">{{data.city.user}}</div>
        </div>
        <div class="d-flex my-1">
            <div class="flex-1">{{$t('actions.info.alliance')}}:</div>
            <div class="flex-2">-</div>
        </div>
        <div class="d-flex my-1">
            <div class="flex-1">{{$t('actions.info.points')}}:</div>
            <div class="flex-2">-</div>
        </div>
    </div>
</template>

<script>
export default {
    name:'Info',
    props:['data']
}
</script>

<style lang="scss" scoped>
    .box{
        font-size: 0.83rem;
        line-height: 0.83rem;
    }
</style>
