// frontend/src/containers/modal/donation/IslandDonation.tsx
import React, { ChangeEvent } from "react";
import { useTranslation } from "react-i18next";

import woodImg from "../../../assets/img/island/img_wood.jpg";
import wineImg from "../../../assets/img/island/img_wine.jpg";
import marbleImg from "../../../assets/img/island/img_marble.jpg";
import glassImg from "../../../assets/img/island/img_glass.jpg";
import sulfurImg from "../../../assets/img/island/img_sulfur.jpg";
import iconWoodImg from "../../../assets/img/icon/icon_wood.png";
import { useCityStore } from "../../../store/cityStore";

interface IslandDonationProps {
    data: {
        type: boolean;
        island_type: number;
        level: number;
        required_wood: number;
        donated: number;
        constructed_at: string | null;
    };
    handleSetDonation: (value: number) => void
}

const IslandDonation: React.FC<IslandDonationProps> = ({ data, handleSetDonation }) => {
    const { t } = useTranslation();
    const [value, setValue] = React.useState(0);
    const resources = useCityStore(state=> state.resources);

    const getImage = () => {
        if (data.type) return woodImg;
        switch (data.island_type) {
            case 1:
                return wineImg;
            case 2:
                return marbleImg;
            case 3:
                return glassImg;
            case 4:
                return sulfurImg;
            default:
                return woodImg;
        }
    };

    const handleInput = (e: ChangeEvent<HTMLInputElement>) => {
        let n = Number(e.target.value);
        if (n > data.required_wood) n = data.required_wood;
        if (n > resources.wood) n = resources.wood;
        if (n < 0) n = 0;
        setValue(n);
    }

    const handleMax = () => {
        let n = data.required_wood;
        if (n > resources.wood) n = resources.wood;
        setValue(n);
    }

    return (
        <div className="py-3 box border rounded bg-yellow-100 text-center text-sm">
            <div className="relative mb-4">
                <img src={getImage()} alt={t("resources.wood")} className="w-full rounded" />
                <div className="absolute bottom-0 right-5 flex">
                    <div className="bg-yellow-300 px-3 py-1 m-auto">
                        <div>{t("modal.donations.level")}</div>
                        <div className="text-xl font-bold">{data.level}</div>
                    </div>
                </div>
            </div>

            <div className="mb-2">
                <div className="font-semibold my-2">{t("modal.donations.required_next_level")}</div>
                <div className="flex items-center pl-5 mb-2">
                    <img src={iconWoodImg} alt={t("resources.wood")} className="w-5 h-5" />
                    <div className="ml-2">{data.required_wood}</div>
                </div>

                <div className="font-semibold my-2">{t("modal.donations.existing")}</div>
                <div className="flex items-center pl-5 mb-2">
                    <img src={iconWoodImg} alt={t("resources.wood")} className="w-5 h-5" />
                    <div className="ml-2">{data.donated}</div>
                </div>
            </div>

            {data.constructed_at === null ? (
                <div className="mt-3">
                    <div className="font-semibold">{t("modal.donations.donate")}</div>
                    <div className="mt-2">
                        <input
                            type="number"
                            className="w-1/2 border rounded px-2 py-1 text-sm"
                            placeholder={t("modal.donations.enter_amount")}
                            value={value > 0 ? value : ''}
                            onChange={handleInput}
                        />
                    </div>
                    <div className="mb-3 text-blue-500 cursor-pointer" onClick={handleMax}>{t("modal.donations.max")}</div>
                    <div className="w-3/4 mx-auto py-1 bg-yellow-300 rounded cursor-pointer hover:bg-yellow-400" onClick={()=> handleSetDonation(value)}>
                        {t("modal.donations.confirm")}
                    </div>
                </div>
            ) : (
                <div className="mt-3">
                    <div>{t("modal.donations.under_construction")}</div>
                    <div>{data.constructed_at}</div>
                </div>
            )}
        </div>
    );
};

export default IslandDonation;

// resources/game/components/modal/Donaciones/IslandDonation.vue
<template>
    <div class="py-3 box">
        <div class="position-relative">
            <img :src="getImage()">
            <div class="box-level">
                <div class="box-level2">
                    <div>Nivel:</div>
                    <div class="level">{{data.level}}</div>
                </div>
            </div>
        </div>
        <div>
            <div class="gtitle my-2">Necesario para el próximo nivel:</div>
            <div class="text-left pl-5 d-flex align-items-center">
                <div><img :src="require('Img/icon/icon_wood.png')"></div>
                <div class="ml-2">{{$money(data.required_wood)}}</div>
            </div>
            <div class="gtitle my-2">Existente:</div>
            <div class="text-left pl-5 d-flex align-items-center">
                <div><img :src="require('Img/icon/icon_wood.png')"></div>
                <div class="ml-2">{{$money(data.donated)}}</div>
            </div>
        </div>
        <div v-if="data.constructed_at==null">
            <div class="gtitle mt-3">Donar</div>
            <div class="mt-2">
                <input class="w-50" type="number" v-model="value">
            </div>
            <div class="mb-3 max" @click='setMax'>max</div>
            <div class="btnGeneral w-75 py-1 m-auto">
                <div @click='confirmar'>Confirmar</div>
            </div>
        </div>
        <div v-else class="mt-3">
            <div>En ampliacion</div>
            <div>{{timeConstruct}}</div>
        </div>
    </div>
</template>

<script>
import axios from 'axios'
import moment from "moment";
import $resources from 'Stores/resources'
import $store from 'Stores/store'
import $city from 'Stores/city'
import $notification from 'Stores/notification'

export default {
    name:'IslandDonation',
    props:['data','reloadDonation'],
    data(){
        return {
            value:0,
            max:0
        }
    },
    methods:{
        setMax(){
            this.value = this.max;
        },
        confirmar(){
            if(this.value!=0){
                axios.put('island/donation/'+this.$route.params.island,{
                    type:this.data.type,
                    wood:this.value,
                    city:this.city_id
                })
                .then(res =>{
                    if(res.data=='ok'){
                        $resources.commit('donate',{wood:this.value})
                        this.setDonation()
                        $notification.commit('show',{advisor:1,type:true})
                    }else{
                        $notification.commit('show',{advisor:1,type:false,message:res.data});
                    }
                })
                .catch(err =>{
                    $notification.commit('show',{advisor:1,type:false,message:err});
                })
            }
        },
        setDonation(){
            this.data.donated += parseInt(this.value);
            this.max = this.max - this.value;
            this.value = 0;
            //Si hay que ampliar lo mostramos
            if(this.max==0){
                this.data.constructed_at = moment(this.now).add(this.data.required_time, 'seconds');
            }
        },
        initMax(){
            var max = this.data.required_wood - this.data.donated;
            this.max = this.wood>max ? max : this.wood;
        },
        getImage(){
             if(this.data.type==1){
                return require('Img/island/img_wood.jpg');
            }else{
                switch(this.data.island_type){
                    case 1:
                        return require('Img/island/img_wine.jpg');
                    break;
                    case 2:
                        return require('Img/island/img_marble.jpg');
                    break;
                    case 3:
                        return require('Img/island/img_glass.jpg');
                    break;
                    case 4:
                        return require('Img/island/img_sulfur.jpg');
                    break;
                }
            }
        }
    },
    computed:{
        wood(){
            return this.$floor($resources.state.wood);
        },
        city_id(){
            return $city.state.city_id;
        },
        timeConstruct() {
            if (this.data.constructed_at != null) {
                return this.$sectotime(moment
                .duration(moment(this.data.constructed_at).diff(moment($store.state.now)))
                .asSeconds());
            }else {
                return null;
            }
        },
        now(){
            return $store.state.now;
        }
    },
    watch:{
         value(newval){
            var control = true;
            if(newval>this.max){
                this.value = this.max;
                control = false;
            }
            if(newval<0||newval==''){
                this.value = 0;
                control = false;
            }
            if(control)
            this.value = newval.toString().replace(/^0+/, '');
        },
        timeConstruct(newval){
            if (newval == "00s") {
                this.constructed_at = null;
                this.reloadDonation();
            }
        },
        data(newval,oldval){
            if(newval.level!=oldval.level){
                this.initMax();
            }
        }
    },
    mounted(){
        this.initMax();
    }
}
</script>

<style lang="scss" scoped>
    .box{
        font-size: 0.83rem;
        text-align: center;
    }
    .box-level{
        position: absolute;
        bottom: 0;
        right: 20px;
        top: 0;
        display: flex;
    }
    .box-level2{
        background: #dfb26f;
        margin: auto;
        padding: 3px 10px 7px;
        line-height: 1.2rem;
    }
    .level{
        font-size: 1.3rem;
    }
    .max{
        cursor: pointer;
        user-select: none;
    }
</style>
