// resources/game/components/layout/navigation/Population.vue
<template>
    <div class="flex-2 d-flex box" :title="$t('resources.population')">
        <div class="population"></div>
        <div>{{$floor(population)}} ({{$floor(population_now)}})</div>
    </div>
</template>

<script>
import axios from 'axios'
import $store from 'Stores/store.js'
import $resources from 'Stores/resources'

export default {
    name:'Population',
    methods:{
        getPopulation(){
            $resources.commit('reloadPopulation');
        },
    },
    computed:{
        city_id(){
            return $store.state.city_id;
        },
        population(){
            return $resources.state.population.population;
        },
        population_now(){
            return $resources.state.population.population_now;
        }
    },
    watch:{
        city_id(newval){
            this.getPopulation()
        }
    },
    mounted(){
        $store.subscribe(action => {
            if (action.type === 'reloadPopulation') {
                this.getPopulation();
            }
        });
    }
}
</script>

<style lang="scss" scoped>
.population{
    background-image: url('~Img/icon/population.png');
    width: 35px;
    height: 23px;
    margin-right: 5px;
}
.box{
    user-select: none;
    justify-content: center;
    align-items: center;
}
</style>

// frontend/src/features/layout/navigation/Population.tsx
import React from "react";
import populationIcon from "../../../assets/img/icon/population.png";

const Population: React.FC = () => {
  return (
    <div className="flex-2 flex select-none justify-center items-center" title="Population">
      <div
        className="w-[35px] h-[23px] mr-[5px] bg-cover"
        style={{ backgroundImage: `url(${populationIcon})` }}
      ></div>
      <div>1000 (500)</div>
    </div>
  );
};

export default Population;
