// resources/game/components/layout/navigation/Resources.vue
<template>
    <div class="flex-1 d-flex resources">
        <div class="flex-1 d-flex">
            <div class="d-flex align-items-center" :title="$t('resources.wood')">
                <img class="mr-1" :src="require('Img/icon/icon_wood.png')">
                <span>{{$money(resources.wood)}}</span>
            </div>
        </div>
        <div class="flex-1 d-flex">
            <div class="d-flex align-items-center" :title="$t('resources.wine')">
                <img class="mr-1" :src="require('Img/icon/icon_wine.png')">
                <span>{{$money(resources.wine)}}</span>
            </div>
        </div>
        <div class="flex-1 d-flex">
            <div class="d-flex align-items-center" :title="$t('resources.marble')">
                <img class="mr-1" :src="require('Img/icon/icon_marble.png')">
                <span>{{$money(resources.marble)}}</span>
            </div>
        </div>
        <div class="flex-1 d-flex">
            <div class="d-flex align-items-center" :title="$t('resources.glass')">
                <img class="mr-1" :src="require('Img/icon/icon_glass.png')">
                <span>{{$money(resources.glass)}}</span>
            </div>
        </div>
        <div class="flex-1 d-flex">
            <div class="d-flex align-items-center" :title="$t('resources.sulfur')">
                <img class="mr-1" :src="require('Img/icon/icon_sulfur.png')">
                <span>{{$money(resources.sulfur)}}</span>
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios'
import $store from 'Stores/store.js'

export default {
    name:'Resources',
    data(){
        return {
            resources:{}
        }
    },
    methods:{
        getResources(){
            axios("city/getResources/" + this.city_id)
            .then(res => {
                this.resources = res.data;
            })
        },
    },
    computed:{
        city_id(){
            return $store.state.city_id;
        }
    },
    watch:{
        city_id(newval){
            this.getResources()
        }
    },
    mounted(){
        $store.subscribe(action => {
            if (action.type === 'reloadResources') {
                this.getResources();
            }
        });
    }
}
</script>

<style lang="scss" scoped>
.resources{
    padding-left: 5px;
    user-select: none;
}
</style>

// frontend/src/features/layout/navigation/Resources.tsx
import React from "react";
import woodIcon from "../../../assets/img/icon/icon_wood.png";
import wineIcon from "../../../assets/img/icon/icon_wine.png";
import marbleIcon from "../../../assets/img/icon/icon_marble.png";
import glassIcon from "../../../assets/img/icon/icon_glass.png";
import sulfurIcon from "../../../assets/img/icon/icon_sulfur.png";

const Resources: React.FC = () => {
  return (
    <div className="flex-1 flex select-none pl-[5px]">
      <div className="flex-1 flex items-center" title="Wood">
        <img className="mr-1" src={woodIcon} alt="Wood" />
        <span>1000</span>
      </div>

      <div className="flex-1 flex items-center" title="Wine">
        <img className="mr-1" src={wineIcon} alt="Wine" />
        <span>500</span>
      </div>

      <div className="flex-1 flex items-center" title="Marble">
        <img className="mr-1" src={marbleIcon} alt="Marble" />
        <span>200</span>
      </div>

      <div className="flex-1 flex items-center" title="Glass">
        <img className="mr-1" src={glassIcon} alt="Glass" />
        <span>150</span>
      </div>

      <div className="flex-1 flex items-center" title="Sulfur">
        <img className="mr-1" src={sulfurIcon} alt="Sulfur" />
        <span>75</span>
      </div>
    </div>
  );
};

export default Resources;
