// frontend/src/components/navigation/Buttons.tsx
import React from "react";

import btnWorldImg from "../../assets/img/icon/btn_world.png";
import btnIslandImg from "../../assets/img/icon/btn_island.jpg";
import btnCityImg from "../../assets/img/icon/btn_city.png";
import { useTranslation } from "react-i18next";

interface ButtonsProps {
    onNavigation: {
        city: () => void,
        island: () => void,
        world: () => void
    }
}

const Buttons: React.FC<ButtonsProps> = ({onNavigation}) => {
    const { t } = useTranslation();
    

    return (
        <div className="flex-1 flex space-x-1 text-[11px] select-none">
            <div
                onClick={() => onNavigation.world()}
                className="flex-1 relative cursor-pointer h-[53px] bg-no-repeat bg-cover"
                title={t("navigation.world")}
                style={{ backgroundImage: `url(${btnWorldImg})` }}
            >
                <div className="absolute bottom-0 w-full text-center">{t("navigation.world")}</div>
            </div>

            <div
                onClick={() => onNavigation.island()}
                className="flex-1 relative cursor-pointer h-[53px] bg-no-repeat bg-cover"
                title={t("navigation.island")}
                style={{ backgroundImage: `url(${btnIslandImg})` }}
            >
                <div className="absolute bottom-0 w-full text-center">{t("navigation.island")}</div>
            </div>

            <div
                onClick={() => onNavigation.city()}
                className="flex-1 relative cursor-pointer h-[56px] bg-no-repeat bg-cover"
                title={t("navigation.city")}
                style={{ backgroundImage: `url(${btnCityImg})` }}
            >
                <div className="absolute bottom-0 w-full text-center">{t("navigation.city")}</div>
            </div>
        </div>
    );
};

export default Buttons;

// resources/game/components/layout/navigation/Buttons.vue
<template>
    <div class="flex-3 d-flex btn-game">
        <div class="flex-1 btn-world" :title="$t('options.navigation.worldTitle')">
            <div class="btn-game-text">{{$t('options.navigation.world')}}</div>
        </div>
        <div class="flex-1 btn-island" @click='toIsland()' :title="$t('options.navigation.islandTitle')">
            <div class="btn-game-text">{{$t('options.navigation.island')}}</div>
        </div>
        <div class="flex-1 btn-city" @click='toCity()' :title="$t('options.navigation.cityTitle')">
            <div class="btn-game-text">{{$t('options.navigation.city')}}</div>
        </div>
    </div>
</template>

<script>
import axios from 'axios'
import $store from 'Stores/store.js'
import { catchAxios } from "Js/util.js";

export default {
    name:'Buttons',
    methods:{
        toIsland(){
            //Verificamos que no este en la misma isla
            if(this.$route.name=='Island'){
                if(this.$route.params.island==this.island_id){
                    return;
                }
            }
            axios('island/'+this.island_id)
            .then(res =>{
                this.$router.push({ name: 'Island', params: { island:this.island_id,data: res.data }})
            })
            .catch(err => {
                catchAxios(err);
            });
        },
        toCity(){
            //Verificamos que no este en la misma ciudad
            if(this.$route.name=='City'){
                if(this.$route.params.city==this.city_id){
                    return;
                }
            }
            axios("building/" + this.city_id)
            .then(res => {
                this.$router.push({ name: 'City', params: { city:this.city_id,buildings: res.data }})
            })
            .catch(err => {
                catchAxios(err);
            });
        }
    },
    computed:{
        city_id(){
            return $store.state.city_id;
        },
        island_id(){
            return $store.state.city_island_id;
        }
    },
}
</script>

<style lang="scss" scoped>
    .btn-game{
        padding: 0px 4px;
        font-size: 11px;
        user-select: none;
    }
    .btn-game-text{
        position: absolute;
        bottom: 1px;
        width: 100%;
        text-align: center;
    }
    .btn-world{
        background-image: url('~Img/icon/btn_world.jpg');
        background-repeat: no-repeat;
        position: relative;
        cursor: pointer;
        height: 53px;
    }
    .btn-island{
        background-image: url('~Img/icon/btn_island.jpg');
        background-repeat: no-repeat;
        position: relative;
        cursor: pointer;
        height: 53px;
    }
    .btn-city{
        background-image: url('~Img/icon/btn_city.png');
        background-repeat: no-repeat;
        position: relative;
        cursor: pointer;
        bottom: 4px;
        height: 58px;
    }
    .btn-city:hover,.btn-island:hover,.btn-world:hover{
        background-position-y: center;
    }
</style>
