// resources/game/views/Island.vue
<template>
<div>
  <div class="islandContainer" v-dragscroll="true" v-autoscroll="'center'">
    <div class="ocean">
      <div class="island">
        <Cities :cities='data.cities' v-if="data.cities"></Cities>
      </div>
    </div>
  </div>
</div>
</template>

<script>
import { dragscroll } from 'vue-dragscroll'
import { autoscroll } from 'vue-autoscroll'
import { catchAxios } from "Js/util.js";

import axios from 'axios'

import Cities from "Components/island/Cities.vue"

export default {
  name: 'Isla',
  directives: {
    dragscroll,
    autoscroll
  },
  components:{
    Cities
  },
  data(){
    return {
      data:{}
    }
  },
  methods:{
      getCities(){
        axios('island/'+this.$route.params.island)
        .then(res =>{
          this.data = res.data;
        })
        .catch(err => {
            catchAxios(err);
        });
    }
  },
  mounted(){
      this.getCities()
  }
};

</script>

<style lang="css" scoped>
.ocean{
  width: 2400px;
  height: 1800px;
  background: url('~Img/island/ocean.jpg');
}
.islandContainer {
  cursor: grab;
  overflow: hidden;
  position: absolute;
  width: 100%;
  height:100%;
}
.island{
  position:relative;
  top: 430px;
  left: 500px;
  width: 1386px;
  height: 924px;
  z-index: 1;
  background: url('~Img/island/0.jpg');
}
</style>

// frontend/src/screens/Island.tsx
import React from "react";
import DragToScroll from "../containers/DragToScroll";

import OceanImg from "../assets/img/island/ocean.jpg";
import IslandImg from "../assets/img/island/0.jpg";
import Layout from "../containers/Layout";
import { useParams } from "react-router-dom";
import { useIslandGetInfo } from "../hooks/useIslandGetInfo";
import IslandCities from "../components/IslandCities";
import IslandResources from "../components/IslandResources";

const IslandUI: React.FC = () => {

    const { islandId } = useParams<{ islandId: string }>();
    const { data } = useIslandGetInfo(Number(islandId));

    return <>
        <Layout />
        <div className="cursor-grab h-full w-full absolute overflow-hidden">
            <DragToScroll className="scroll-container" centerVertical>
                <div
                    className="relative w-[2400px] h-[1800px] bg-cover bg-no-repeat"
                    style={{ backgroundImage: `url(${OceanImg})` }}
                >
                    <div
                        className="absolute top-[430px] left-[500px] w-[1386px] h-[924px] bg-cover bg-no-repeat z-10"
                        style={{ backgroundImage: `url(${IslandImg})` }}
                    >
                        {
                            data && <>
                                <IslandCities 
                                    id={data.id}
                                    name={data.name}
                                    x={data.x}
                                    y={data.y}
                                    cities={data.cities}
                                />
                                <IslandResources
                                    type={data.type}
                                    islandId={data.id}
                                    levelForest={data.levelForest}
                                    levelMine={data.levelMine}
                                />
                            </>
                        }
                    </div>
                </div>
            </DragToScroll>
        </div>
    </>
};

export default IslandUI;
