// resources/game/components/modal/Donaciones/IslandResources.vue
<template>
    <div class="box">
        <div class="text-justify mb-3 texto">{{getTitle()}}</div>
        <div class="gtitle text-center">{{$t('island.workers')}}</div>
        <div class="d-flex mt-3">
            <div class="flex-1 citizen">
                <img class="mb-2" :src="require('Img/island/citizen.png')">
                <div class="valores">{{population_available}}</div>
            </div>
            <div class="flex-3">
                <div class="d-flex texto">
                    <div class="flex-1">
                        <div>{{$t('other.income')}}: </div>
                        <div>{{population_available*3}} <img :src="require('Img/icon/icon_gold.png')"> {{$t('other.perHour')}}</div>
                    </div>
                    <div class="flex-1 text-right">
                        <div>{{$t('other.production')}}: </div>
                        <div>{{value}} <img :src="getIcon()"> {{$t('other.perHour')}}</div>
                    </div>
                </div>
                <div class="d-flex my-3">
                    <div class="flex-1 min" @click='setMin'></div>
                    <div class="flex-10"><vue-slider ref="slider" :height='16' silent :max='max' v-model="value"></vue-slider></div>
                    <div class="flex-1 max" @click='setMax'></div>
                </div>
                <div class="d-flex justify-content-center">
                    <div class="campo">
                        <input class="w-100" type="number" v-model="value">
                    </div>
                    <div class="btnGeneral px-3 ml-3 d-flex">
                        <div class="m-auto" @click='confirmar'>{{$t('other.confirm')}}</div>
                    </div>
                </div>
            </div>
            <div class="flex-1 workers">
                <img class="mb-2" :src="getWorkerIcon()">
                <div class="valores">{{value}}</div>
            </div>
        </div>
         <div>
            <div class="gtitle mt-5 mb-3 text-center">{{$t('island.islandCities')}}</div>
            <vue-table-dynamic :params="params"></vue-table-dynamic>
        </div>
    </div>
</template>

<script>
import axios from 'axios'
import VueSlider from 'vue-slider-component'
import VueTableDynamic from 'vue-table-dynamic'
import 'vue-slider-component/theme/default.css'
import $resources from 'Stores/resources'
import $store from 'Stores/store'
import $notification from 'Stores/notification'

export default {
    name:'IslandResources',
    props:['data'],
    components: {
        VueSlider,
        VueTableDynamic
    },
    data(){
        return {
            value:0,
            population:0,
            max:0,
            workers:0,
            params: {
                data: [],
                header: 'row',
                sort: [0,1,2,3,4]
            }
        }
    },
    methods:{
        setMin(){
            this.$refs.slider.setValue(0)
        },
        setMax(){
            this.$refs.slider.setValue(this.max)
        },
        confirmar(){
            axios.post('island/setWorker/'+this.city_id,{
                type:this.data.info.type,
                workers:this.value
            })
            .then(res =>{
                if(res.data=='ok'){
                    $notification.commit('show',{advisor:1,type:true});
                    if(this.data.info.type === 1){
                        $resources.commit('setWorkerForest',{population:this.population_available,worker_forest:this.value})
                    }else{
                        $resources.commit('setWorkerMine',{population:this.population_available,worker_mine:this.value})
                    }
                }else{
                    $notification.commit('show',{advisor:1,type:false,message:res.data});
                }
            })
            .catch(err =>{
                $notification.commit('show',{advisor:1,type:false,message:err});
            })
        },
        iniData(){
            this.workers = this.data.info.type === 1 ? this.worker_forest : this.worker_mine;
            this.population = this.population_aux + this.workers;
            this.max = this.data.info.workers>this.population ? this.population : this.data.info.workers;
            this.value = this.workers;
            this.params.data = [];
            this.params.data.push(this.$t('island.donationTable'));
            this.params.data.push(...this.data.donations);
        },
        getTitle(){
            if(this.data.info.type==1){
                return this.$t('island.forestTitle');
            }else{
                switch(this.data.info.island_type){
                    case 1:
                        return this.$t('island.vinesTitle');
                    break;
                    case 2:
                        return this.$t('island.quarryTitle');
                    break;
                    case 3:
                        return this.$t('island.crystalTitle');
                    break;
                    case 4:
                        return this.$t('island.sulfurTitle');
                    break;
                }
            }
        },
        getIcon(){
            if(this.data.info.type==1){
                return require('Img/icon/icon_wood.png');
            }else{
                switch(this.data.info.island_type){
                    case 1:
                        return require('Img/icon/icon_wine.png');
                    break;
                    case 2:
                        return require('Img/icon/icon_marble.png');
                    break;
                    case 3:
                        return require('Img/icon/icon_glass.png');
                    break;
                    case 4:
                        return require('Img/icon/icon_sulfur.png');
                    break;
                }
            }
        },
        getWorkerIcon(){
            if(this.data.info.type==1){
                return require('Img/island/worker.png');
            }else{
                return require('Img/island/worker_mine.png');
            }
        }
    },
    computed:{
        population_available(){
            return this.population - this.value;
        },
        population_aux(){
            return this.$floor($resources.state.population.population);
        },
        worker_forest(){
            return this.$floor($resources.state.population.worker_forest);
        },
        worker_mine(){
            return this.$floor($resources.state.population.worker_mine);
        },
        city_id(){
            return $store.state.city_id;
        }
    },
    watch:{
        value(newval){
            var control = true;
            if(newval>this.max){
                this.value = this.max;
                control = false;
            }
            if(newval<0||newval==''){
                this.value = 0;
                control = false;
            }
            if(control)
            this.value = newval.toString().replace(/^0+/, '');
        },
        data(newval,oldval){
            if(newval.info.level!=oldval.info.level || newval.info.type != oldval.info.type){
                this.iniData()
            }
        }
    },
    beforeMount(){
        this.iniData()
    }
}
</script>

<style lang="scss" scoped>
    @import "~Sass/modal";
    .citizen,.workers{
        position: relative;
        display: flex;
        justify-content: center;
        align-self: flex-start;
    }
    .min{
        background-image: url('~Img/icon/btn_min.png');
        background-repeat: no-repeat;
        background-position: center;
        cursor: pointer;
    }
    .max{
        background-image: url('~Img/icon/btn_max.png');
        background-repeat: no-repeat;
        background-position: center;
        cursor: pointer;
    }
    .campo{
        width: 75px;
    }
</style>

// frontend/src/containers/modal/donation/IslandResources.tsx
import React from "react";
import { useTranslation } from "react-i18next";

import citizenImg from "../../../assets/img/island/citizen.png";
import workerImg from "../../../assets/img/island/worker.png";
import workerMineImg from "../../../assets/img/island/worker_mine.png";
import woodIcon from "../../../assets/img/icon/icon_wood.png";
import wineIcon from "../../../assets/img/icon/icon_wine.png";
import marbleIcon from "../../../assets/img/icon/icon_marble.png";
import glassIcon from "../../../assets/img/icon/icon_glass.png";
import sulfurIcon from "../../../assets/img/icon/icon_sulfur.png";

interface IslandInfo {
  type: number;
  island_type: number;
}

export interface IslandData {
  info: IslandInfo;
  donations: any[];
}

interface IslandResourcesProps {
  data: IslandData;
}

const IslandResources: React.FC<IslandResourcesProps> = ({ data }) => {
  const { t } = useTranslation();

  const value = 0;
  const max = 100;
  const populationAvailable = 50;

  const getTitle = () => {
    if (data.info.type === 1) return t("modal.donations.forestTitle");
    switch (data.info.island_type) {
      case 1:
        return t("modal.donations.vinesTitle");
      case 2:
        return t("modal.donations.quarryTitle");
      case 3:
        return t("modal.donations.crystalTitle");
      case 4:
        return t("modal.donations.sulfurTitle");
      default:
        return "";
    }
  };

  const getIcon = () => {
    if (data.info.type === 1) return woodIcon;
    switch (data.info.island_type) {
      case 1:
        return wineIcon;
      case 2:
        return marbleIcon;
      case 3:
        return glassIcon;
      case 4:
        return sulfurIcon;
      default:
        return "";
    }
  };

  const getWorkerIcon = () => {
    if (data.info.type === 1) return workerImg;
    return workerMineImg;
  };

  return (
    <div className="p-4">
      <div className="text-justify mb-3">{getTitle()}</div>
      <div className="text-center font-semibold">{t("modal.donations.workers")}</div>

      <div className="flex mt-3">
        <div className="flex-1 flex flex-col items-center">
          <img src={citizenImg} className="mb-2 w-10 h-10" alt="citizen" />
          <div className="text-lg font-bold">{populationAvailable}</div>
        </div>

        <div className="flex-3 flex flex-col ml-4">
          <div className="flex justify-between text-sm mb-3">
            <div>
              <div>{t("modal.donations.income")}:</div>
              <div className="flex items-center">
                100 <img src={sulfurIcon} className="w-4 h-4 ml-1" alt="gold" /> {t("modal.donations.perHour")}
              </div>
            </div>
            <div className="text-right">
              <div>{t("modal.donations.production")}:</div>
              <div className="flex items-center">
                50 <img src={getIcon()} className="w-4 h-4 ml-1" alt="resource" /> {t("modal.donations.perHour")}
              </div>
            </div>
          </div>

          <div className="flex items-center mb-3">
            <div className="w-6 h-6 bg-gray-300 cursor-pointer mr-2"></div>
            {/* <VueSlider
              className="flex-1 h-4"
              min={0}
              max={max}
              value={value}
              renderThumb={(props) => <div {...props} className="bg-yellow-500 w-4 h-4 rounded-full" />}
            /> */}
            <div className="w-6 h-6 bg-gray-300 cursor-pointer ml-2"></div>
          </div>

          <div className="flex justify-center">
            <input
              type="number"
              className="border border-gray-400 rounded w-20 px-2 py-1"
              value={value}
              readOnly
            />
            <button className="ml-3 bg-yellow-500 text-black px-3 py-1 rounded">{t("modal.donations.confirm")}</button>
          </div>
        </div>

        <div className="flex-1 flex flex-col items-center">
          <img src={getWorkerIcon()} className="mb-2 w-10 h-10" alt="worker" />
          <div className="text-lg font-bold">{value}</div>
        </div>
      </div>

      <div className="mt-5 text-center font-semibold">{t("modal.donations.islandCities")}</div>
      <div className="mt-2">
        {/* <TableDynamic params={data.donations} /> */}
      </div>
    </div>
  );
};

export default IslandResources;
