// resources/game/views/Island.vue
<template>
<div>
  <div class="islandContainer" v-dragscroll="true" v-autoscroll="'center'">
    <div class="ocean">
      <div class="island">
        <Cities :data='data' v-if="data.cities"></Cities>
        <Resources :data='data'></Resources>
      </div>
    </div>
  </div>
</div>
</template>

<script>
import { dragscroll } from 'vue-dragscroll'
import { autoscroll } from 'vue-autoscroll'
import $notification from 'Stores/notification'

import axios from 'axios'

import Cities from "Components/island/Cities.vue"
import Resources from "Components/island/Resources.vue"

export default {
  name: 'Isla',
  directives: {
    dragscroll,
    autoscroll
  },
  components:{
    Cities,
    Resources
  },
  data(){
    return {
      data:{}
    }
  },
  beforeMount(){
    if(this.$route.params.data!=undefined){
      this.data = this.$route.params.data;
    }else{
      axios('island/'+this.$route.params.island)
      .then(res =>{
        this.data = res.data;
      })
      .catch(err => {
          $notification.commit('show',{advisor:1,type:false,message:err});
      });
    }
  },
};

</script>

<style lang="css" scoped>
.ocean{
  width: 2400px;
  height: 1800px;
  background: url('~Img/island/ocean.jpg');
}
.islandContainer {
  cursor: grab;
  overflow: hidden;
  position: absolute;
  width: 100%;
  height:100%;
}
.island{
  position:relative;
  top: 430px;
  left: 500px;
  width: 1386px;
  height: 924px;
  z-index: 1;
  background: url('~Img/island/0.jpg');
}
</style>

// frontend/src/views/Island.tsx
import React from "react";
import DragToScroll from "../components/DragToScroll";

import OceanImg from "../assets/img/island/ocean.jpg";
import IslandImg from "../assets/img/island/0.jpg";
import Layout from "../features/layout/Layout";
// import Cities from "../components/island/Cities";
// import Resources from "../components/island/Resources";

const IslandUI: React.FC = () => {
    return <>
        <Layout />
        <div className="cursor-grab h-full w-full absolute overflow-hidden">
            <DragToScroll className="scroll-container" centerVertical>
                <div
                    className="relative w-[2400px] h-[1800px] bg-cover bg-no-repeat"
                    style={{ backgroundImage: `url(${OceanImg})` }}
                >
                    <div
                        className="absolute top-[430px] left-[500px] w-[1386px] h-[924px] bg-cover bg-no-repeat z-10"
                        style={{ backgroundImage: `url(${IslandImg})` }}
                    >
                        {/* <Cities />
            <Resources /> */}
                    </div>
                </div>
            </DragToScroll>
        </div>
    </>
};

export default IslandUI;
